apiVersion: v1
kind: Service
metadata:
  name: headless-test
  namespace: openshift-ingress-canary
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    ingresscanary.operator.openshift.io/daemonset-ingresscanary: canary_controller
